/**
 * Copyright (C) 2009 - 2009 by OpenGamma Inc.
 *
 * Please see distribution for license.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OpenGamma.Fudge
{
    /// <summary>
    /// A Fudge-specific subclass of <see cref="Exception"/> for all exceptions
    /// generated by Fudge. 
    /// </summary>
    public class FudgeRuntimeException : Exception
    {
        public FudgeRuntimeException(string message)
            : base(message)
        {
        }

        public FudgeRuntimeException(string message, Exception cause)
            : base(message, cause)
        {
        }
    }
}
