/* <!--
 * Copyright (C) 2009 - 2009 by OpenGamma Inc. and other contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * -->
 */
using System;
using System.Collections.Generic;
using System.Text;

namespace Fudge
{
    /// <summary>
    /// A Fudge-specific subclass of <see cref="Exception"/> for all exceptions
    /// generated by Fudge. 
    /// </summary>
    public class FudgeRuntimeException : Exception
    {
        /// <summary>
        /// Creates a new exception object.
        /// </summary>
        /// <param name="message">error message</param>
        public FudgeRuntimeException(string message)
            : base(message)
        {
        }

        /// <summary>
        /// Creates a new exception object in response to an underlying error.
        /// </summary>
        /// <param name="message">error message</param>
        /// <param name="cause">underlying error</param>
        public FudgeRuntimeException(string message, Exception cause)
            : base(message, cause)
        {
        }
    }
}
